onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - better-sqlite3
  - esbuild
  - lefthook
  - prisma
  - prisma-zod-generator
  - unrs-resolver
